GET https://ap-sever.herokuapp.com/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdjZWZiOWI2ODI5MzE5OTY0ZGVkMTciLCJpYXQiOjE2MzY3Mjc4MzF9.16xWSBBNNoHdCwSnYtBoFgsqnnujvtyBknk6Ry6c_9c
Content-Type: application/json

###

POST  https://ap-sever.herokuapp.com/users/store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdjZWZiOWI2ODI5MzE5OTY0ZGVkMTciLCJpYXQiOjE2MzY3Mjc4MzF9.16xWSBBNNoHdCwSnYtBoFgsqnnujvtyBknk6Ry6c_9c
Content-Type: application/json

{
    "fullName": "testt",
    "username": "tesst",
    "password": "tesst",
    "userCode": "test",
    "email": "tesst@gmail.com",
    "phone": "tesst",
    "address": "tesst",
    "gender": "Nam",
    "rolesId": "617ce9b1ad1d4cf09c207337",
    "majorsId": "617d7aa1c5c0dfd2a8714e06"
}

###

PUT https://ap-sever.herokuapp.com/users/618f5e0cc374fbbfccfe8b84
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdjZWZiOWI2ODI5MzE5OTY0ZGVkMTciLCJpYXQiOjE2MzY3Mjc4MzF9.16xWSBBNNoHdCwSnYtBoFgsqnnujvtyBknk6Ry6c_9c
Content-Type: application/json

{
    "fullName": "dcm tung",
    "username": "tesst",
    "password": "tesst",
    "userCode": "test",
    "email": "tesst@gmail.com",
    "phone": "tesst",
    "address": "tesst",
    "nationality": "Việt Nam",
    "gender": "Nam",
    "DoB": "13/07/2001",
    "rolesId": "617ce9b1ad1d4cf09c207337",
    "majorsId": "617d7aa1c5c0dfd2a8714e06"
}

###

DELETE https://ap-sever.herokuapp.com/users/618e7e8c4a740437204c89be
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdjZWZiOWI2ODI5MzE5OTY0ZGVkMTciLCJpYXQiOjE2MzY3Mjc4MzF9.16xWSBBNNoHdCwSnYtBoFgsqnnujvtyBknk6Ry6c_9c

###

GET  https://ap-sever.herokuapp.com/scores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdjZWZiOWI2ODI5MzE5OTY0ZGVkMTciLCJpYXQiOjE2MzY3Mjc4MzF9.16xWSBBNNoHdCwSnYtBoFgsqnnujvtyBknk6Ry6c_9c
###

GET  https://ap-sever.herokuapp.com/scores/61821b32e2c474ccfd471a7c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdkMDY3ODFjMzFjNTE1YWVlYWNmOGIiLCJpYXQiOjE2Mzc1OTM4MzF9._k0JX5ecI_LmNE1br9q2APjMk1GznrIJRY4SXNLeYuE

###
GET https://ap-sever.herokuapp.com/scores/class/61821b32e2c474ccfd471a7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdkMDgxZDFjMzFjNTE1YWVlYWNmOTMiLCJpYXQiOjE2Mzc0MTM3NTB9.xbQLZeSwd5bTC5X7XvhAqJhXEpoKMA_6RxJ1603LdeU
###

POST https://ap-sever.herokuapp.com/courses/store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdjZWZiOWI2ODI5MzE5OTY0ZGVkMTciLCJpYXQiOjE2MzY3Mjc4MzF9.16xWSBBNNoHdCwSnYtBoFgsqnnujvtyBknk6Ry6c_9c
Content-Type: application/json

{
"description": "test",
"image": "1636182023282.jpg",
"level": "test",
"majorsId": "617d7aa1c5c0dfd2a8714e06",
"name": "test",
}


###
GET https://ap-sever.herokuapp.com/courses?page=1&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdjZWZiOWI2ODI5MzE5OTY0ZGVkMTciLCJpYXQiOjE2MzY3Mjc4MzF9.16xWSBBNNoHdCwSnYtBoFgsqnnujvtyBknk6Ry6c_9c
Content-Type: application/json
